services:
  CI_CD:
    container_name: postgres
    restart: unless-stopped
    image: postgres:12
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: actions_db
    volumes:
      - ./postgres_data/:/var/lib/postgresql/data


