name: Spring Boot Project CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-java-project:
    name: Build and Deploy Spring Boot Application
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 22
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '22'

      - name: Setup postgres with docker-compose
        run: |
          docker compose up -d

      - name: Build App
        run: |
          mvn clean
          mvn -B package --file pom.xml

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: .
          # Instead of Dockerfile use the pom build plugin to build an image of the application.
          file: Dockerfile
          push: true
          no-cache: true  # avoid cached build issues
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/myapp:0.1.0




